# Generated by Django 2.0.5 on 2018-06-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAppCategoryMapings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(choices=[('1', 'is_primary'), ('0', 'None')], default=0)),
                ('app_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.AppCategories')),
            ],
        ),
        migrations.CreateModel(
            name='TempAppCoverPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_pic', models.ImageField(default=None, upload_to='cover_pics')),
                ('is_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('app_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.AppCategories')),
            ],
        ),
        migrations.CreateModel(
            name='TempAppMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.TextField()),
                ('is_physical', models.BooleanField(default=True)),
                ('store_address', models.TextField()),
                ('lat', models.CharField(blank=True, max_length=255, null=True)),
                ('long', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no1', models.BigIntegerField()),
                ('contact_no2', models.BigIntegerField()),
                ('contact_no3', models.BigIntegerField()),
                ('is_allose_open', models.BooleanField(choices=[('1', 'is_allose_open'), ('0', 'None')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempAppProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppMasters')),
            ],
        ),
        migrations.CreateModel(
            name='TempAppProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('hide_org_price_status', models.BooleanField(choices=[('1', 'hide'), ('0', 'None')], default=0)),
                ('packing_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('app_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppMasters')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppProductCategories')),
            ],
        ),
        migrations.CreateModel(
            name='TempProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('app_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppProducts')),
            ],
        ),
        migrations.AddField(
            model_name='tempappcategorymapings',
            name='appmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppMasters'),
        ),
    ]
