# Generated by Django 2.0.5 on 2018-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappmasters',
            name='contact_no1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='contact_no2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='contact_no3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='locality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
