# Generated by Django 2.0.5 on 2018-06-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0002_auto_20180630_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappcategorymapings',
            name='appmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_category', to='temp_app.TempAppMasters'),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='logo',
            field=models.ImageField(default=None, upload_to='logo_pics'),
        ),
    ]
