# Generated by Django 2.0.5 on 2018-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0002_auto_20180717_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempappmasters',
            name='business_est_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
