# Generated by Django 2.0.5 on 2018-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0003_auto_20180630_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempappmasters',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='logo',
            field=models.ImageField(default=None, upload_to='logos'),
        ),
    ]
