# Generated by Django 2.0.5 on 2018-07-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180717_1656'),
        ('temp_app', '0003_tempappmasters_business_est_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempappmasters',
            name='owner_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Designations'),
        ),
        migrations.AddField(
            model_name='tempappmasters',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempappmasters',
            name='owner_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='owners_pic'),
        ),
    ]
