# Generated by Django 2.0.5 on 2018-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0004_auto_20180702_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=50)),
                ('user_locality', models.CharField(blank=True, max_length=50, null=True)),
                ('user_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('users_pic', models.ImageField(default=None, upload_to='users_pic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
