# Generated by Django 2.0.5 on 2018-07-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0004_auto_20180726_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempappimgs',
            name='src',
        ),
    ]
