# Generated by Django 2.0.5 on 2018-07-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0005_remove_tempappimgs_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappmasters',
            name='owner_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designations.Designations'),
        ),
        migrations.AlterField(
            model_name='tempusers',
            name='owner_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designations.Designations'),
        ),
    ]
