# Generated by Django 2.0.5 on 2018-07-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0007_tempimgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempImgs',
            new_name='TempAppImgs',
        ),
    ]
