# Generated by Django 2.0.5 on 2018-07-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0009_tempappimgs_app_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempappmasters',
            old_name='is_allose_open',
            new_name='is_always_open',
        ),
    ]
