# Generated by Django 2.0.5 on 2018-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0010_auto_20180704_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappmasters',
            name='business_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='tempappmasters',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
