# Generated by Django 2.0.5 on 2018-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0011_auto_20180704_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempusers',
            old_name='user_designation',
            new_name='owner_designation',
        ),
        migrations.RenameField(
            model_name='tempusers',
            old_name='username',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='tempusers',
            name='user_locality',
        ),
        migrations.RemoveField(
            model_name='tempusers',
            name='users_pic',
        ),
        migrations.AddField(
            model_name='tempusers',
            name='owner_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users_pic'),
        ),
    ]
