# Generated by Django 2.0.5 on 2018-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0012_auto_20180704_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempusers',
            name='contact_no',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tempusers',
            name='email_id',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
