# Generated by Django 2.0.5 on 2018-07-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0013_auto_20180704_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappcategorymapings',
            name='app_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_category', to='app_category.AppCategories'),
        ),
        migrations.AlterField(
            model_name='tempappcategorymapings',
            name='appmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppMasters'),
        ),
    ]
