# Generated by Django 2.0.5 on 2018-07-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0014_auto_20180704_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappcategorymapings',
            name='appmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appmaster_appmapping', to='temp_app.TempAppMasters'),
        ),
    ]
