# Generated by Django 2.0.5 on 2018-07-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0017_tempappmasters_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappmasters',
            name='app_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
