# Generated by Django 2.0.5 on 2018-07-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0021_auto_20180709_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempappproducts',
            name='app_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppMasters'),
        ),
        migrations.AlterField(
            model_name='tempappproducts',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temp_app.TempAppProductCategories'),
        ),
    ]
