# Generated by Django 2.0.5 on 2018-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0023_auto_20180709_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempappcategorymapings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
