# Generated by Django 2.0.5 on 2018-07-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0024_tempappcategorymapings_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempappcategorymapings',
            name='is_deleted',
        ),
    ]
