# Generated by Django 2.0.5 on 2018-07-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0025_remove_tempappcategorymapings_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempappproductcategories',
            unique_together=set(),
        ),
    ]
