# Generated by Django 2.0.5 on 2018-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='users_pic',
            field=models.ImageField(default=None, upload_to='users_pic'),
        ),
    ]
