# Generated by Django 2.0.5 on 2018-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180727_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='franchise_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
