# Generated by Django 2.0.5 on 2018-07-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetails_users_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='parent',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.States'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
