# Generated by Django 2.0.5 on 2018-08-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetails_franchise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='otm_send_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
