# Generated by Django 2.0.5 on 2018-07-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180704_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
