# Generated by Django 2.0.5 on 2018-08-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180801_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='otp_send_time',
        ),
    ]
