# Generated by Django 2.0.5 on 2018-07-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_auto_20180728_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appproducts',
            name='hide_org_price_status',
            field=models.BooleanField(choices=[('1', 'hide'), ('0', 'None')], default=0),
        ),
    ]
