# Generated by Django 2.0.5 on 2018-07-18 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_auto_20180718_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apppayment',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apppayment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
