# Generated by Django 2.0.5 on 2018-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
