# Generated by Django 2.0.5 on 2018-07-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180721_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerappmastermapping',
            unique_together=set(),
        ),
    ]
