# Generated by Django 2.0.5 on 2018-07-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180710_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('email', 'contact_no')},
        ),
    ]
