# Generated by Django 2.0.5 on 2018-07-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0012_appmasters_business_est_year'),
        ('states', '0001_initial'),
        ('customers', '0006_auto_20180711_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAppMasterMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_master', to='app_masters.AppMasters')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.Customers')),
            ],
        ),
        migrations.RenameModel(
            old_name='customer_address',
            new_name='CustomerAddress',
        ),
    ]
