# Generated by Django 2.0.5 on 2018-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20180713_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerappmastermapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
