# Generated by Django 2.0.5 on 2018-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcoverphotos',
            name='cover_pic',
            field=models.ImageField(default=None, upload_to='cover_pics'),
        ),
    ]
