# Generated by Django 2.0.5 on 2018-07-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designations', '0001_initial'),
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmasters',
            name='owner_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designations.Designations'),
        ),
        migrations.AddField(
            model_name='appmasters',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appmasters',
            name='owner_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='owners_pic'),
        ),
    ]
