# Generated by Django 2.0.5 on 2018-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0002_auto_20180629_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmasters',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
