# Generated by Django 2.0.5 on 2018-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0003_appmasters_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmasters',
            name='contact_no1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmasters',
            name='contact_no2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmasters',
            name='contact_no3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmasters',
            name='locality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmasters',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
