# Generated by Django 2.0.5 on 2018-07-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0004_auto_20180704_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppImgages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_images', models.ImageField(default=None, upload_to='app_images')),
                ('src', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.AppMasters')),
            ],
        ),
    ]
