# Generated by Django 2.0.5 on 2018-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0005_appimgages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmasters',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos'),
        ),
    ]
