# Generated by Django 2.0.5 on 2018-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0006_auto_20180706_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmasters',
            name='app_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
