# Generated by Django 2.0.5 on 2018-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0007_appmasters_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmasters',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
