# Generated by Django 2.0.5 on 2018-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0008_appmasters_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategorymapings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
