# Generated by Django 2.0.5 on 2018-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0010_remove_appcategorymapings_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmasters',
            name='visiting_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
