# Generated by Django 2.0.5 on 2018-07-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0011_appmasters_visiting_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmasters',
            name='business_est_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
