# Generated by Django 2.0.5 on 2018-07-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0012_appmasters_business_est_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appimgages',
            old_name='app',
            new_name='appmaster',
        ),
    ]
