# Generated by Django 2.0.5 on 2018-07-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0013_auto_20180713_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmasters',
            old_name='is_allose_open',
            new_name='is_always_open',
        ),
        migrations.RenameField(
            model_name='appmasters',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='appmasters',
            old_name='is_physical',
            new_name='is_physical_store',
        ),
    ]
