# Generated by Django 2.0.5 on 2018-07-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0014_auto_20180713_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmasters',
            name='business_est_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
