# Generated by Django 2.0.5 on 2018-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategories',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category_cover_image'),
        ),
        migrations.AddField(
            model_name='appcategories',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category_icon'),
        ),
    ]
