# Generated by Django 2.0.5 on 2018-07-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0001_initial'),
        ('uom', '0001_initial'),
        ('customers', '0001_initial'),
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('IGST', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CGST', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('GST', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('packaging_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.AppMasters')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='customers.Customers')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.AppProducts'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='uom_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uom_currency', to='uom.Currency'),
        ),
    ]
