# Generated by Django 2.0.5 on 2018-07-28 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0002_remove_appmasters_owner_logo'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='appmaster',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_masters.AppMasters'),
        ),
    ]
