# Generated by Django 2.0.5 on 2018-07-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180728_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='app_products.AppProducts'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='uom_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uom_currency_details', to='uom.Currency'),
        ),
    ]
