# Generated by Django 2.0.5 on 2018-07-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_type', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('receiver_id', models.IntegerField()),
                ('receiver_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sending_time', models.DateTimeField(auto_now_add=True)),
                ('receiving_time', models.DateTimeField(blank=True, null=True)),
                ('view_time', models.DateTimeField(blank=True, null=True)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_masters.AppMasters')),
            ],
        ),
    ]
