# Generated by Django 2.0.5 on 2018-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmessenger',
            name='msg_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
