# Generated by Django 2.0.5 on 2018-07-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messenger', '0003_chatsession_chatsessionmember_chatsessionmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='owner_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='owner_type',
            new_name='user_type',
        ),
    ]
